name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build directories
        run: |
          bigDirectories=("java-collections-ru" "java-oop-ru" "java-web-ru" "java-advanced-ru" "java-spring-ru")
          for bigDir in "${bigDirectories[@]}"; do
          # retrieve directory containing gradlew file & replace {} with it
            projectDirectories=$(find "$bigDir" -type f -name "gradlew" -exec dirname {} \;) 
            for projectDir in $projectDirectories; do
          # navigate to dir & temporarily assign it as working directory
              pushd "$projectDir"
              gradle build
          # return to the previous working directory
              popd
            done
          done