name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build advanced/asynchrony
        working-directory: java-advanced-ru/asynchrony
        run: gradle build

      - name: Build oop/errors
        working-directory: java-oop-ru/errors
        run: gradle build

      - name: Build collections/lists
        working-directory: java-collections-ru/generics
        run: gradle build
